name: ContrabandCrate
version: 1.0
api: [3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
main: ContrabandCrate\Crate
author: ["EmeraldAssasinYT"]

commands:
 cratekey:
  description: "§r§bCube§aX §cCrate System Developed By EmeraldAssasinYT"
  permission: "givecratekey.cmd"
  default: false
